"""Added active column to products

Revision ID: c92e4d76b43e
Revises: 8e0d8ceef24d
Create Date: 2025-02-28 11:43:49.828207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92e4d76b43e'
down_revision: Union[str, None] = '8e0d8ceef24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'active')
    # ### end Alembic commands ###
